---
AWS_REGION: "us-east-1"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID: "372026249783"
JOB_TYPE: "TRAINING"
WORLD_NAME: "reInvent2019_wide"
TRACK_DIRECTION_CLOCKWISE: "false"
CHANGE_START_POSITION: true
ALTERNATE_DRIVING_DIRECTION: false
TRAINING_JOB_ARN: "arn:aws:deepracer:us-east-1:480936841767:training_job/B0d4THMvQT6tt8Jkk54L3w"
METRIC_NAME: "TrainingRewardScore"
METRIC_NAMESPACE: "AWSDeepRacer"
SAGEMAKER_SHARED_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SAGEMAKER_SHARED_S3_PREFIX: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/sagemaker-robomaker-artifacts/"
REWARD_FILE_S3_KEY: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/reward_function.py"
MODEL_METADATA_FILE_S3_KEY: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/model_metadata.json"
METRICS_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
METRICS_S3_OBJECT_KEY: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/metrics/training/training-20230608143740-B0d4THMvQT6tt8Jkk54L3w.json"
MP4_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
MP4_S3_OBJECT_PREFIX: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/videos/training/training-20230608143741-B0d4THMvQT6tt8Jkk54L3w/"
SIMTRACE_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SIMTRACE_S3_PREFIX: "data-327c3f07-1290-4f24-a471-a1f223b0a2c1/models/b5a7b150-5553-46a2-9d0c-9a6cb1e0495c/sim-trace/training/"
S3_KMS_CMK_ARN: "arn:aws:kms:us-east-1:372026249783:key/fc23d4bf-a026-4faf-a38c-1970f4c5f541"
KINESIS_VIDEO_STREAM_NAME: "dr-kvs-372026249783-20230608143740-aaee8efe-b1a7-4e34-8e60-a562b370d1b3"
VIDEO_JOB_TYPE: "TRAINING"
MODEL_NAME: "ddd-ver6"
RACER_NAME: "StructuredArithmetic#2448"
RACE_TYPE: "TIME_TRIAL"
